### ISSUE TITLE
挑战必须通关一次才解锁

### ISSUE THREAD

**Issue by LingASDJ** [endlesssolitude/ShatteredPD-DetailedDesc#1]
在我们测试发现，新版本在未通关之前没有挑战按钮。这是致命的，望您在空暇时间修复错误。其他错误我们尚未看见，有的话会第一时间发送Issuse给你。也祝你新年快乐，虎年大吉。

**Comment by endlesssolitude** [comment]
solved in 1.1
Well I often forget to unlock challenges for first installs because i have no direct access to this case. Tkx.
